mode: deployment
replicaCount: 1
image:
  repository: otel/opentelemetry-collector-contrib
presets:
  kubernetesAttributes:
    enabled: true
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  processors:
    batch: {}
    resource:
      attributes:
        - key: k8s.cluster.name
          value: ${cluster_name}
          action: upsert
  exporters:
    logging:
      verbosity: basic
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [resource, batch]
        exporters: [logging]
      metrics:
        receivers: [otlp]
        processors: [resource, batch]
        exporters: [logging]
      logs:
        receivers: [otlp]
        processors: [resource, batch]
        exporters: [logging]
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
