project:
  name: oficina

ecs:
  name: oficina
  containerPort: 8080
  desiredCount: 1
  launchType: FARGATE

loadBalancer:
  name: oficina
  scheme: internal
  listenerPort: 80
  healthPath: /health
  deregistrationDelaySeconds: 30

services:
  cadastro:
    name: oficina-cadastro
    targetGroupName: oficina-cadastro
    logGroupName: /ecs/oficina/cadastro
  estoque:
    name: oficina-estoque
    targetGroupName: oficina-estoque
    logGroupName: /ecs/oficina/estoque
  ordens:
    name: oficina-ordens-servico
    targetGroupName: oficina-ordens
    logGroupName: /ecs/oficina/ordens

ecr:
  cadastro: oficina-cadastro
  estoque: oficina-estoque
  ordens: oficina-ordens-servico
  dbBootstrap: oficina-db-bootstrap
  imageTagMutability: IMMUTABLE
  scanOnPush: true
  retainedImages: 20

sqs:
  longPollingSeconds: 20
  visibilityTimeoutSeconds: 60
  maxReceiveCount: 3
  messageRetentionSeconds: 345600
  dlqRetentionSeconds: 1209600
